// src/dashboard/logic/fieldLabels.js
import { cleanLabel } from './formatters';

export const FIELD_LABELS = {
  'gearing.spur': 'Gearing: Spur Gear',
  'gearing.pinion': 'Gearing: Pinion Gear',
  'gearing.tireDia': 'Gearing: Tire Dia.',
  'gearing.transRatio': 'Gearing: Tran Ratio',
  'tires.lf': 'Tires: LF Tire',
  'tires.rf': 'Tires: RF Tire',
  'tires.lr': 'Tires: LR Tire',
  'tires.rr': 'Tires: RR Tire',
  'suspension.hubTopLF': 'Susp: LF Top Hub/Kingpin',
  'suspension.hubBottomLF': 'Susp: LF Bottom Hub/Kingpin',
  'suspension.hubTopRF': 'Susp: RF Top Hub/Kingpin',
  'suspension.hubBottomRF': 'Susp: RF Bottom Hub/Kingpin',
  'suspension.hubTopLR': 'Susp: LR Top Hub/Kingpin',
  'suspension.hubBottomLR': 'Susp: LR Bottom Hub/Kingpin',
  'suspension.hubTopRR': 'Susp: RR Top Hub/Kingpin',
  'suspension.hubBottomRR': 'Susp: RR Bottom Hub/Kingpin',
  'suspension.lfSpring': 'Suspension: LF Spring',
  'suspension.rfSpring': 'Suspension: RF Spring',
  'suspension.lrSpring': 'Suspension: LR Spring',
  'suspension.rrSpring': 'Suspension: RR Spring',
  'suspension.centerSpring': 'Suspension: Center Spring',
  'suspension.lfOil': 'Suspension: LF Oil',
  'suspension.rfOil': 'Suspension: RF Oil',
  'suspension.lrOil': 'Suspension: LR Oil',
  'suspension.rrOil': 'Suspension: RR Oil',
  'suspension.centerOil': 'Suspension: Center Oil',
  'suspension.lfTop': 'Suspension: Shock Pos LF Top',
  'suspension.lfBottom': 'Suspension: Shock Pos LF Bottom',
  'suspension.rfTop': 'Suspension: Shock Pos RF Top',
  'suspension.rfBottom': 'Suspension: Shock Pos RF Bottom',
  'suspension.lrTop': 'Suspension: Shock Pos LR Top',
  'suspension.lrBottom': 'Suspension: Shock Pos LR Bottom',
  'suspension.rrTop': 'Suspension: Shock Pos RR Top',
  'suspension.rrBottom': 'Suspension: Shock Pos RR Bottom',
  'suspension.centerFront': 'Suspension: Shock Pos Center Front',
  'suspension.centerRear': 'Suspension: Shock Pos Center Rear',
  'suspension.lfHole': 'Suspension: LF Hole',
  'suspension.rfHole': 'Suspension: RF Hole',
  'suspension.lrHole': 'Suspension: LR Hole',
  'suspension.rrHole': 'Suspension: RR Hole',
  'suspension.centerHole': 'Suspension: Center Hole',
  'suspension.lfHeight': 'Suspension: LF Height',
  'suspension.rfHeight': 'Suspension: RF Height',
  'suspension.lrHeight': 'Suspension: LR Height',
  'suspension.rrHeight': 'Suspension: RR Height',
  'suspension.podHeight': 'Suspension: Pod Height',
  'suspension.lfDroop': 'Suspension: LF Droop',
  'suspension.rfDroop': 'Suspension: RF Droop',
  'suspension.lrDroop': 'Suspension: LR Droop',
  'suspension.rrDroop': 'Suspension: RR Droop',
  'suspension.podDroop': 'Suspension: Pod Droop',
  'geometry.lfCamber': 'Geometry: LF Camber',
  'geometry.rfCamber': 'Geometry: RF Camber',
  'geometry.lrCamber': 'Geometry: LR Camber',
  'geometry.rrCamber': 'Geometry: RR Camber',
  'geometry.lfCaster': 'Geometry: LF Caster',
  'geometry.rfCaster': 'Geometry: RF Caster',
  'geometry.frontToe': 'Geometry: Front Toe',
  'geometry.rearToe': 'Geometry: Rear Toe',
  'geometry.tweak': 'Geometry: Tweak',
  'cornerWeights.lf': 'Corner Weight: LF Weight',
  'cornerWeights.rf': 'Corner Weight: RF Weight',
  'cornerWeights.lr': 'Corner Weight: LR Weight',
  'cornerWeights.rr': 'Corner Weight: RR Weight',
};

export function prettyField(fieldPath) {
  const key = String(fieldPath || '').trim();
  return FIELD_LABELS[key] || cleanLabel(key);
}
