import { Dimensions, Platform, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');
const isNarrow = width < 390;
const chassisMinHeight = Math.max(450, height - 205);

export const setupColors = {
  bg: '#050506',
  bg0: '#08090d',
  bg2: '#0a0b0f',
  panel: '#101116',
  panel2: '#14161d',
  panel3: '#1a1d26',
  border: '#8b5cf6',
  borderSoft: '#2a2f3a',
  purple: '#8b5cf6',
  purple2: '#c084fc',
  purpleDark: '#7c3aed',
  purpleSoft: 'rgba(139, 92, 246, 0.18)',
  purpleWash: 'rgba(139, 92, 246, 0.10)',
  text: '#f8fafc',
  textMuted: '#c7ceda',
  muted: '#a7afbd',
  dim: '#717987',
  danger: '#ff5c7a',
  success: '#76f0b5',
  input: '#0b0c11',
};

const maxPageWidth = 760;
const maxEditorWidth = 820;

export const setupStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: setupColors.bg,
  },
  screen: {
    flex: 1,
    backgroundColor: setupColors.bg,
  },
  keyboardRoot: {
    flex: 1,
    backgroundColor: setupColors.bg,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: isNarrow ? 12 : 14,
    paddingTop: 6,
    paddingBottom: 22,
    width: '100%',
    maxWidth: maxPageWidth,
    alignSelf: 'center',
  },
  editorScrollContent: {
    flexGrow: 1,
    paddingHorizontal: isNarrow ? 10 : 12,
    paddingTop: 4,
    paddingBottom: 18,
    width: '100%',
    maxWidth: maxEditorWidth,
    alignSelf: 'center',
  },
  editorMainArea: {
    flex: 1,
    minHeight: 0,
  },
  editorNoScrollContent: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    maxWidth: maxEditorWidth,
    alignSelf: 'center',
    paddingHorizontal: isNarrow ? 10 : 12,
    paddingTop: 4,
    paddingBottom: 0,
  },

  pageHeader: {
    width: '100%',
    maxWidth: maxPageWidth,
    alignSelf: 'center',
    paddingHorizontal: isNarrow ? 12 : 14,
    paddingTop: 8,
    paddingBottom: 4,
    backgroundColor: setupColors.bg,
  },
  eyebrow: {
    color: setupColors.purple,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.15,
    textTransform: 'uppercase',
    marginBottom: 0,
  },
  title: {
    color: setupColors.text,
    fontSize: isNarrow ? 25 : 28,
    lineHeight: isNarrow ? 29 : 32,
    fontWeight: '900',
    letterSpacing: 0.1,
  },
  subtitle: {
    color: setupColors.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 8,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 9,
  },
  headerTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  headerSpacer: {
    width: 62,
    minHeight: 36,
  },
  headerActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
    flexShrink: 0,
  },

  countBadge: {
    alignSelf: 'flex-start',
    marginTop: 9,
    backgroundColor: setupColors.purpleWash,
    borderColor: setupColors.purple,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 5,
  },
  countBadgeText: {
    color: setupColors.text,
    fontSize: 11,
    fontWeight: '900',
  },
  listTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 13,
    marginBottom: 2,
  },
  listTitle: {
    color: setupColors.text,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.1,
  },
  listHint: {
    color: setupColors.muted,
    fontSize: 10,
    fontWeight: '800',
  },

  card: {
    backgroundColor: setupColors.panel,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    borderRadius: 14,
    padding: isNarrow ? 9 : 10,
    marginTop: 9,
    shadowColor: '#000',
    shadowOpacity: 0.20,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  cardList: {
    position: 'relative',
    overflow: 'hidden',
    paddingLeft: isNarrow ? 14 : 16,
  },
  cardAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: setupColors.purple,
  },
  cardTight: {
    backgroundColor: setupColors.panel,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    borderRadius: 13,
    padding: 9,
    marginTop: 8,
  },
  formSection: {
    backgroundColor: 'transparent',
    borderBottomColor: setupColors.borderSoft,
    borderBottomWidth: 1,
    paddingTop: 8,
    paddingBottom: 10,
    marginTop: 4,
  },
  cardPressed: {
    opacity: 0.84,
    transform: [{ scale: 0.995 }],
  },
  cardTitle: {
    color: setupColors.text,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '900',
  },
  cardSubtitle: {
    color: setupColors.muted,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 2,
    fontWeight: '700',
  },
  cardMeta: {
    color: setupColors.dim,
    fontSize: 10,
    lineHeight: 14,
    marginTop: 3,
    fontWeight: '800',
  },

  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
    marginBottom: 7,
    paddingBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: setupColors.borderSoft,
  },
  sectionTitle: {
    color: setupColors.text,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.15,
  },
  sectionHint: {
    color: setupColors.purple2,
    fontSize: 10,
    fontWeight: '900',
  },
  groupTitle: {
    color: setupColors.purple2,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.65,
    textTransform: 'uppercase',
    marginTop: 9,
    marginBottom: 4,
  },

  row: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
  },
  wrapRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  grid2: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 6,
  },
  gridItemHalf: {
    width: '48.8%',
  },

  fieldWrap: {
    marginBottom: 7,
  },
  label: {
    color: setupColors.muted,
    fontSize: 10,
    fontWeight: '800',
    marginBottom: 3,
    letterSpacing: 0.15,
  },
  input: {
    minHeight: 34,
    color: setupColors.text,
    backgroundColor: setupColors.input,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: Platform.OS === 'ios' ? 8 : 5,
    fontSize: 13,
    fontWeight: '700',
  },
  inputFocused: {
    borderColor: setupColors.purple,
    backgroundColor: '#120d1c',
  },
  inputMultiline: {
    minHeight: 62,
    paddingTop: 9,
    textAlignVertical: 'top',
  },
  readOnlyInput: {
    opacity: 0.72,
  },

  calcBox: {
    backgroundColor: setupColors.purpleWash,
    borderColor: setupColors.border,
    borderWidth: 1,
    borderRadius: 12,
    padding: 8,
    marginTop: 2,
    marginBottom: 7,
  },
  calcLabel: {
    color: setupColors.purple2,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  calcValue: {
    color: setupColors.text,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 2,
  },
  calcSubValue: {
    color: setupColors.muted,
    fontSize: 10,
    fontWeight: '800',
    marginTop: 2,
  },

  button: {
    minHeight: 34,
    borderRadius: 11,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: setupColors.purpleDark,
    borderWidth: 1,
    borderColor: setupColors.purple,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  buttonSecondary: {
    backgroundColor: setupColors.panel,
    borderColor: setupColors.borderSoft,
  },
  buttonGhost: {
    backgroundColor: 'transparent',
    borderColor: setupColors.borderSoft,
  },
  buttonDanger: {
    backgroundColor: 'rgba(255, 92, 122, 0.12)',
    borderColor: 'rgba(255, 92, 122, 0.55)',
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  topBackButton: {
    minWidth: 62,
    paddingHorizontal: 10,
  },
  topActionButton: {
    minWidth: 64,
    paddingHorizontal: 12,
  },
  buttonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
  },
  buttonSecondaryText: {
    color: setupColors.text,
    fontSize: 12,
    fontWeight: '900',
  },
  buttonDangerText: {
    color: setupColors.danger,
    fontSize: 11,
    fontWeight: '900',
  },
  dataToolRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  dataToolButton: {
    flex: 1,
    minHeight: 38,
  },

  editorPageHeader: {
    width: '100%',
    maxWidth: maxEditorWidth,
    alignSelf: 'center',
    paddingHorizontal: isNarrow ? 12 : 14,
    paddingTop: 8,
    paddingBottom: 6,
    backgroundColor: setupColors.bg,
    zIndex: 10,
  },
  fixedTopBar: {
    width: '100%',
    maxWidth: maxEditorWidth,
    alignSelf: 'center',
    paddingHorizontal: isNarrow ? 12 : 14,
    paddingTop: 8,
    paddingBottom: 6,
    backgroundColor: setupColors.bg,
    zIndex: 10,
  },
  editorMeta: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 4,
  },
  editorTitle: {
    color: setupColors.text,
    fontSize: 17,
    lineHeight: 20,
    fontWeight: '900',
    textAlign: 'left',
  },
  editorSubtitle: {
    color: setupColors.muted,
    fontSize: 10,
    fontWeight: '800',
    marginTop: 1,
    textAlign: 'left',
  },
  editorScreenTitle: {
    color: setupColors.text,
    fontSize: isNarrow ? 21 : 24,
    lineHeight: isNarrow ? 24 : 27,
    fontWeight: '900',
    letterSpacing: 0.05,
  },
  editorScreenSubtitle: {
    color: setupColors.muted,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '800',
    marginTop: 1,
  },

  tabBarWrap: {
    width: '100%',
    maxWidth: maxEditorWidth,
    alignSelf: 'center',
    marginTop: 5,
    backgroundColor: setupColors.bg,
    borderBottomWidth: 1,
    borderBottomColor: setupColors.borderSoft,
    paddingVertical: 5,
  },
  tabScrollContent: {
    paddingHorizontal: isNarrow ? 10 : 12,
    gap: 6,
  },
  tabPill: {
    minHeight: 29,
    borderRadius: 999,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: setupColors.panel,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
  },
  tabPillActive: {
    backgroundColor: setupColors.purpleDark,
    borderColor: setupColors.purple,
  },
  tabText: {
    color: setupColors.muted,
    fontSize: 10,
    fontWeight: '900',
  },
  tabTextActive: {
    color: setupColors.text,
  },

  modernTabShell: {
    width: '100%',
    maxWidth: maxEditorWidth,
    alignSelf: 'center',
    backgroundColor: setupColors.bg,
    paddingHorizontal: isNarrow ? 10 : 12,
    paddingTop: 2,
    paddingBottom: 8,
    zIndex: 9,
  },
  modernTabTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 5,
  },
  modernTabCaption: {
    color: setupColors.purple,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1.05,
  },
  modernTabCurrent: {
    flex: 1,
    textAlign: 'right',
    color: setupColors.muted,
    fontSize: 10,
    fontWeight: '900',
  },
  modernTabFrame: {
    backgroundColor: '#090d16',
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    borderRadius: 18,
    paddingVertical: 5,
    paddingHorizontal: 5,
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  modernTabScrollContent: {
    gap: 6,
    paddingRight: 2,
  },
  modernTabPill: {
    minHeight: 35,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 999,
    paddingLeft: 7,
    paddingRight: 11,
    backgroundColor: '#0d1422',
    borderColor: '#1c2940',
    borderWidth: 1,
    position: 'relative',
  },
  modernTabPillActive: {
    backgroundColor: setupColors.purpleDark,
    borderColor: setupColors.purple2,
    shadowColor: setupColors.purple,
    shadowOpacity: 0.25,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  modernTabPillPressed: {
    opacity: 0.86,
    transform: [{ scale: 0.985 }],
  },
  modernTabCodeWrap: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: setupColors.purpleWash,
    borderColor: 'rgba(168, 85, 247, 0.28)',
    borderWidth: 1,
  },
  modernTabCodeWrapActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    borderColor: 'rgba(255, 255, 255, 0.26)',
  },
  modernTabCode: {
    color: setupColors.purple2,
    fontSize: 9,
    fontWeight: '900',
  },
  modernTabCodeActive: {
    color: setupColors.text,
  },
  modernTabText: {
    color: setupColors.muted,
    fontSize: 11,
    fontWeight: '900',
  },
  modernTabTextActive: {
    color: setupColors.text,
  },
  modernTabGlowDot: {
    position: 'absolute',
    right: 6,
    top: 6,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: setupColors.text,
    opacity: 0.92,
  },

  badge: {
    alignSelf: 'center',
    backgroundColor: setupColors.purpleWash,
    borderColor: setupColors.purple,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 7,
    minWidth: 74,
    maxWidth: 104,
  },
  badgeText: {
    color: setupColors.text,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '900',
    textAlign: 'center',
  },

  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 4,
  },
  statBox: {
    flexGrow: 1,
    flexBasis: '47%',
    backgroundColor: setupColors.bg2,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    borderRadius: 10,
    padding: 8,
  },
  statLabel: {
    color: setupColors.purple2,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.65,
    textTransform: 'uppercase',
  },
  statValue: {
    color: setupColors.text,
    fontSize: 13,
    fontWeight: '900',
    marginTop: 4,
  },

  emptyText: {
    color: setupColors.muted,
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
  },
  readOnlyBanner: {
    width: '100%',
    maxWidth: maxEditorWidth,
    alignSelf: 'center',
    backgroundColor: setupColors.purpleWash,
    borderColor: setupColors.border,
    borderWidth: 1,
    borderRadius: 10,
    padding: 8,
    marginTop: 5,
  },
  readOnlyBannerText: {
    color: setupColors.muted,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },

  quickPanel: {
    marginTop: 4,
    marginBottom: 1,
  },
  quickTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 7,
  },
  quickTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  quickEyebrow: {
    color: setupColors.purple,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.95,
    textTransform: 'uppercase',
  },
  quickTitle: {
    color: setupColors.text,
    fontSize: 17,
    lineHeight: 20,
    fontWeight: '900',
    marginTop: 1,
  },
  miniButton: {
    minHeight: 31,
    borderRadius: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: setupColors.purpleDark,
    borderColor: setupColors.purple,
    borderWidth: 1,
  },
  miniButtonText: {
    color: setupColors.text,
    fontSize: 11,
    fontWeight: '900',
  },
  quickGrid: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'stretch',
  },
  quickRunLineWrap: {
    flex: 1,
    minWidth: 0,
  },
  referenceTileWide: {
    flex: 1,
    minHeight: 52,
    borderRadius: 14,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    backgroundColor: setupColors.panel,
    paddingLeft: 15,
    paddingRight: 10,
    paddingVertical: 8,
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  referenceTileValue: {
    color: setupColors.text,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '900',
    marginTop: 3,
  },
  rolloutTile: {
    width: isNarrow ? 92 : 106,
    minHeight: 52,
    borderRadius: 14,
    borderColor: setupColors.purple,
    borderWidth: 1,
    backgroundColor: setupColors.panel,
    paddingLeft: 15,
    paddingRight: 8,
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'flex-start',
    position: 'relative',
    overflow: 'hidden',
  },
  rolloutTileLabel: {
    color: setupColors.purple2,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.75,
    textTransform: 'uppercase',
  },
  rolloutTileValue: {
    color: setupColors.text,
    fontSize: 19,
    lineHeight: 23,
    fontWeight: '900',
    marginTop: 2,
  },

  chassisShell: {
    flex: 1,
    minHeight: 0,
    marginTop: 7,
  },
  chassisHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 8,
  },
  chassisTitle: {
    color: setupColors.text,
    fontSize: 17,
    lineHeight: 20,
    fontWeight: '900',
    marginTop: 1,
  },
  chassisHint: {
    color: setupColors.muted,
    fontSize: 10,
    fontWeight: '800',
    marginTop: 4,
  },
  chassisProfileBadge: {
    maxWidth: isNarrow ? 132 : 170,
    borderRadius: 999,
    borderColor: setupColors.purple,
    borderWidth: 1,
    backgroundColor: setupColors.purpleWash,
    paddingHorizontal: 9,
    paddingVertical: 5,
    alignItems: 'flex-end',
  },
  chassisProfileBadgeText: {
    color: setupColors.text,
    fontSize: 9,
    lineHeight: 11,
    fontWeight: '900',
    letterSpacing: 0.45,
    textTransform: 'uppercase',
  },
  chassisFrame: {
    flex: 1,
    minHeight: 0,
    paddingTop: 2,
    paddingBottom: 4,
    justifyContent: 'flex-start',
    gap: 10,
    overflow: 'visible',
  },
  chassisAxleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: isNarrow ? 13 : 18,
  },
  chassisMiddleRow: {
    flex: 0,
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: isNarrow ? 8 : 12,
    paddingVertical: 0,
    paddingHorizontal: 0,
    overflow: 'visible',
  },
  crossWeightCenter: {
    width: isNarrow ? 124 : 142,
    minHeight: 60,
    borderRadius: 13,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    backgroundColor: setupColors.panel,
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 14,
    paddingRight: 12,
    paddingVertical: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  crossWeightLabel: {
    color: setupColors.purple2,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  crossWeightValue: {
    color: setupColors.text,
    fontSize: 17,
    lineHeight: 20,
    fontWeight: '900',
    marginTop: 1,
  },
  crossWeightSub: {
    color: setupColors.dim,
    fontSize: 9,
    fontWeight: '900',
    marginTop: 1,
    textTransform: 'uppercase',
  },
  electronicsSideButton: {
    width: isNarrow ? 92 : 104,
    minHeight: 108,
    borderRadius: 14,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    backgroundColor: setupColors.panel,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 14,
    paddingRight: 7,
    paddingVertical: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  centerDiffSideButton: {
    width: isNarrow ? 92 : 104,
    minHeight: 108,
    borderRadius: 14,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    backgroundColor: setupColors.panel,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 14,
    paddingRight: 7,
    paddingVertical: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  electronicsSideSpacer: {
    width: isNarrow ? 92 : 104,
    minHeight: 108,
  },
  chassisRail: {
    flex: 1,
    height: 0,
    opacity: 0,
  },
  chassisItemAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: setupColors.purple,
  },
  frontBulkhead: {
    flex: 1,
    alignSelf: 'center',
    minHeight: 58,
    borderRadius: 14,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    backgroundColor: setupColors.panel,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 14,
    paddingRight: 8,
    paddingVertical: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  rearBulkhead: {
    flex: 1,
    alignSelf: 'center',
    minHeight: 58,
    borderRadius: 14,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    backgroundColor: setupColors.panel,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 14,
    paddingRight: 8,
    paddingVertical: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  rearPodBetweenWheels: {
    minHeight: 76,
    maxWidth: isNarrow ? 118 : 138,
  },
  rearBulkheadPlaceholder: {
    flex: 1,
    minHeight: 58,
    opacity: 0,
  },
  rearAreaWrap: {
    marginTop: 0,
    marginBottom: 0,
    gap: 10,
    overflow: 'visible',
  },
  rearGearStack: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 0,
    marginBottom: 0,
  },
  rearAxleRow: {
    alignItems: 'center',
  },
  gearBulkhead: {
    width: isNarrow ? 128 : 148,
    minHeight: 72,
    borderRadius: 14,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    backgroundColor: setupColors.panel,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 16,
    paddingRight: 11,
    paddingVertical: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  rearPodBulkhead: {
    borderColor: setupColors.borderSoft,
  },

  chassisPartLabel: {
    color: setupColors.text,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  chassisPartValue: {
    color: setupColors.muted,
    fontSize: 10,
    fontWeight: '800',
    marginTop: 4,
  },
  chassisPartSubValue: {
    color: setupColors.dim,
    fontSize: 9,
    fontWeight: '800',
    marginTop: 2,
  },
  centerPodButton: {
    width: isNarrow ? 118 : 138,
    minHeight: 66,
    borderRadius: 15,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    backgroundColor: setupColors.panel,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 15,
    paddingRight: 10,
    paddingVertical: 10,
    position: 'relative',
    overflow: 'hidden',
  },
  drivetrainButton: {
    backgroundColor: setupColors.panel,
    borderColor: setupColors.borderSoft,
  },
  centerPodText: {
    color: setupColors.text,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0.15,
  },
  centerPodSub: {
    color: setupColors.muted,
    fontSize: 10,
    fontWeight: '800',
    marginTop: 4,
  },
  cornerHotspot: {
    width: isNarrow ? 110 : 126,
    minHeight: isNarrow ? 160 : 174,
    borderRadius: 14,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    backgroundColor: setupColors.panel,
    paddingLeft: 13,
    paddingRight: 8,
    paddingVertical: 10,
    position: 'relative',
    overflow: 'hidden',
  },
  tireShape: {
    width: 62,
    height: 34,
    borderRadius: 9,
    borderColor: setupColors.purple2,
    borderWidth: 1,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 12,
  },
  cornerHotspotCopy: {
    width: '100%',
    minWidth: 0,
  },
  cornerHotspotTitle: {
    color: setupColors.text,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  cornerHotspotLine: {
    width: '100%',
    color: setupColors.text,
    fontSize: 13,
    fontWeight: '900',
    marginTop: 1,
  },
  cornerHotspotSub: {
    width: '100%',
    color: setupColors.muted,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 2,
  },

  editorBottomBar: {
    width: '100%',
    backgroundColor: setupColors.bg,
    paddingHorizontal: isNarrow ? 10 : 12,
    paddingTop: 7,
    paddingBottom: Platform.OS === 'ios' ? 30 : 24,
  },
  editorBottomActionRow: {
    width: '100%',
    maxWidth: maxEditorWidth,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  mapActionRow: {
    flexDirection: 'row',
    gap: 7,
    marginTop: 9,
  },
  mapActionButton: {
    flex: 1,
    minHeight: 60,
    borderRadius: 14,
    borderWidth: 1,
    borderLeftWidth: 4,
    borderColor: setupColors.borderSoft,
    borderLeftColor: setupColors.purple,
    backgroundColor: setupColors.panel,
    paddingLeft: 10,
    paddingRight: 9,
    paddingVertical: 8,
    justifyContent: 'center',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  mapActionLabel: {
    color: setupColors.purple2,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  mapActionValue: {
    color: setupColors.text,
    fontSize: 15,
    fontWeight: '900',
    marginTop: 3,
  },
  fastAccessGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  fastButton: {
    flexGrow: 1,
    flexBasis: '47%',
    minHeight: 58,
    borderRadius: 12,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    backgroundColor: setupColors.panel,
    paddingHorizontal: 10,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  fastButtonTitle: {
    color: setupColors.text,
    fontSize: 13,
    fontWeight: '900',
  },
  fastButtonSubtitle: {
    color: setupColors.muted,
    fontSize: 10,
    fontWeight: '800',
    marginTop: 3,
  },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.72)',
    justifyContent: 'center',
    paddingHorizontal: isNarrow ? 10 : 14,
    paddingVertical: 14,
  },
  modalCard: {
    width: '100%',
    maxWidth: maxEditorWidth,
    alignSelf: 'center',
    maxHeight: '88%',
    minHeight: '48%',
    borderRadius: 20,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    backgroundColor: setupColors.bg2,
    overflow: 'hidden',
  },
  modalHandle: {
    alignSelf: 'center',
    width: 52,
    height: 4,
    borderRadius: 999,
    backgroundColor: setupColors.purple,
    marginTop: 8,
    marginBottom: 4,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: isNarrow ? 12 : 14,
    paddingTop: 8,
    paddingBottom: 10,
    backgroundColor: setupColors.panel,
    borderBottomColor: setupColors.borderSoft,
    borderBottomWidth: 1,
  },
  modalEyebrow: {
    color: setupColors.purple,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  modalTitle: {
    color: setupColors.text,
    fontSize: 19,
    lineHeight: 23,
    fontWeight: '900',
    marginTop: 1,
  },
  modalCloseButton: {
    minWidth: 66,
  },
  modalScroll: {
    flex: 1,
  },
  modalScrollContent: {
    paddingHorizontal: isNarrow ? 10 : 12,
    paddingTop: 2,
    paddingBottom: 118,
  },

  confirmBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.76)',
    justifyContent: 'center',
    paddingHorizontal: isNarrow ? 14 : 18,
  },
  confirmCard: {
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
    borderRadius: 22,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    backgroundColor: setupColors.panel,
    paddingHorizontal: isNarrow ? 15 : 18,
    paddingTop: 18,
    paddingBottom: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 9 },
    elevation: 8,
  },

  exportBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.66)',
    justifyContent: 'center',
    paddingHorizontal: isNarrow ? 14 : 18,
  },
  exportBackdropScroll: {
    flex: 1,
    width: '100%',
  },
  exportBackdropScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
  },
  exportPromptCard: {
    width: '100%',
    maxWidth: 420,
    maxHeight: '92%',
    alignSelf: 'center',
    borderRadius: 20,
    borderColor: setupColors.borderSoft,
    borderWidth: 1,
    backgroundColor: setupColors.panel,
    paddingHorizontal: isNarrow ? 14 : 17,
    paddingTop: 14,
    paddingBottom: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 9 },
    elevation: 8,
  },
  confirmAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
    backgroundColor: setupColors.purple,
  },
  confirmEyebrow: {
    color: setupColors.purple2,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.05,
    textTransform: 'uppercase',
    marginLeft: 4,
  },
  confirmTitle: {
    color: setupColors.text,
    fontSize: isNarrow ? 22 : 24,
    lineHeight: isNarrow ? 26 : 28,
    fontWeight: '900',
    marginTop: 5,
    marginLeft: 4,
  },
  confirmMessage: {
    color: setupColors.muted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    marginTop: 8,
    marginLeft: 4,
  },
  exportTitle: {
    fontSize: isNarrow ? 21 : 23,
    lineHeight: isNarrow ? 24 : 27,
  },
  exportMessage: {
    marginTop: 6,
    fontSize: 12,
    lineHeight: 16,
  },
  confirmActionStack: {
    marginTop: 16,
    gap: 9,
  },
  confirmPrimaryButton: {
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: setupColors.purple2,
    backgroundColor: setupColors.purpleDark,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: setupColors.purple,
    shadowOpacity: 0.24,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  confirmPrimaryText: {
    color: setupColors.text,
    fontSize: 15,
    fontWeight: '900',
  },
  confirmSecondaryRow: {
    flexDirection: 'row',
    gap: 8,
  },
  confirmSecondaryButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: setupColors.borderSoft,
    backgroundColor: setupColors.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmDangerButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: 'rgba(255, 92, 122, 0.45)',
    backgroundColor: 'rgba(255, 92, 122, 0.10)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmSecondaryText: {
    color: setupColors.text,
    fontSize: 12,
    fontWeight: '900',
  },
  confirmDangerText: {
    color: setupColors.danger,
    fontSize: 12,
    fontWeight: '900',
  },


  exportChoiceStack: {
    marginTop: 10,
    gap: 8,
  },
  exportChoiceButton: {
    position: 'relative',
    overflow: 'hidden',
    minHeight: 54,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: setupColors.borderSoft,
    backgroundColor: setupColors.bg2,
    paddingVertical: 8,
    paddingLeft: 18,
    paddingRight: 12,
    justifyContent: 'center',
  },
  exportChoiceAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
    backgroundColor: setupColors.purple,
  },
  exportChoiceTitle: {
    color: setupColors.text,
    fontSize: 16,
    lineHeight: 19,
    fontWeight: '900',
  },
  exportChoiceSub: {
    color: setupColors.muted,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '800',
    marginTop: 3,
  },
  exportCancelButton: {
    marginTop: 10,
    minHeight: 42,
    width: '100%',
  },


  topButtonCluster: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  topMiniActionButton: {
    minWidth: 62,
    paddingHorizontal: 9,
  },
  setupCarCard: {
    backgroundColor: setupColors.bg0,
    borderColor: 'rgba(168, 92, 255, 0.38)',
    borderWidth: 1,
    marginLeft: 12,
    marginBottom: 8,
    paddingVertical: 8,
    paddingLeft: 14,
    paddingRight: 9,
    borderRadius: 14,
  },
  setupCarAccent: {
    position: 'absolute',
    left: 0,
    top: 8,
    bottom: 8,
    width: 3,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    backgroundColor: setupColors.purple2,
  },
  setupCarKicker: {
    color: setupColors.purple2,
    fontSize: 8,
    lineHeight: 10,
    fontWeight: '900',
    letterSpacing: 0.9,
    marginRight: 7,
  },
  setupCarCompactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  setupCarHeaderLine: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
    minWidth: 0,
  },
  setupCarDate: {
    flex: 1,
    color: setupColors.textMuted,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '700',
  },
  setupCarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  setupCarTextPress: {
    flex: 1,
    minWidth: 0,
    borderRadius: 10,
    paddingVertical: 1,
  },
  setupCarActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  setupCarActionFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
  },
  setupCarInlineActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
  },
  setupCarSmallButton: {
    minWidth: 54,
    minHeight: 30,
    paddingHorizontal: 8,
  },
  setupCarMiniButton: {
    minWidth: 50,
    minHeight: 30,
    paddingHorizontal: 8,
  },
  setupCarCopyButton: {
    flex: 1.1,
    minHeight: 32,
    paddingHorizontal: 9,
  },
  setupCarEditButton: {
    flex: 0.75,
    minHeight: 32,
    paddingHorizontal: 9,
  },
  importReviewCard: {
    maxHeight: '88%',
    paddingBottom: 14,
  },
  importSourceBox: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: setupColors.borderSoft,
    backgroundColor: setupColors.bg2,
    paddingHorizontal: 13,
    paddingVertical: 11,
    marginTop: 12,
  },
  importSourcePairRow: {
    flexDirection: 'row',
    gap: 9,
    marginTop: 7,
  },
  importSourcePair: {
    flex: 1,
    minWidth: 0,
  },
  importSourceSmallLabel: {
    color: setupColors.muted,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  importSourceLabel: {
    color: setupColors.purple2,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  importSourceTitle: {
    color: setupColors.text,
    fontSize: 16,
    lineHeight: 19,
    fontWeight: '900',
    marginTop: 4,
  },
  importSourceMeta: {
    color: setupColors.muted,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '800',
    marginTop: 2,
  },
  importSectionLabel: {
    color: setupColors.purple2,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    marginTop: 12,
    marginLeft: 4,
  },
  importTargetGrid: {
    flexDirection: 'row',
    gap: 9,
    marginTop: 10,
  },
  importTargetButton: {
    flex: 1,
    minHeight: 58,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: setupColors.borderSoft,
    backgroundColor: setupColors.bg2,
    paddingHorizontal: 12,
    paddingVertical: 9,
    justifyContent: 'center',
  },
  importTargetLabel: {
    color: setupColors.purple2,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  importTargetValue: {
    color: setupColors.text,
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '900',
    marginTop: 4,
  },
  importTargetHint: {
    color: setupColors.muted,
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  importOptionScroll: {
    maxHeight: 210,
    marginTop: 10,
  },
  importOptionScrollContent: {
    gap: 7,
    paddingBottom: 2,
  },
  importOptionRow: {
    position: 'relative',
    overflow: 'hidden',
    minHeight: 56,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: setupColors.borderSoft,
    backgroundColor: setupColors.bg2,
    paddingLeft: 15,
    paddingRight: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  importOptionRowSelected: {
    borderColor: setupColors.purple,
    backgroundColor: setupColors.purpleWash,
  },
  importOptionAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: setupColors.purple,
  },
  importOptionTitle: {
    color: setupColors.text,
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '900',
  },
  importOptionMeta: {
    color: setupColors.muted,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '800',
    marginTop: 2,
  },
  importOptionCheck: {
    color: setupColors.purple2,
    fontSize: 10,
    fontWeight: '900',
  },

  importSourceBoxCompact: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: setupColors.borderSoft,
    backgroundColor: setupColors.bg2,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginTop: 10,
  },
  importWizardProgressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 11,
    marginBottom: 2,
  },
  importWizardStepPill: {
    minHeight: 26,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: setupColors.borderSoft,
    backgroundColor: setupColors.bg2,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  importWizardStepPillActive: {
    borderColor: setupColors.purple,
    backgroundColor: setupColors.purpleWash,
  },
  importWizardStepText: {
    color: setupColors.text,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.55,
    textTransform: 'uppercase',
  },
  importWizardStepLine: {
    flex: 1,
    height: 2,
    borderRadius: 2,
    backgroundColor: setupColors.borderSoft,
  },
  importWizardStepLineActive: {
    backgroundColor: setupColors.purple,
  },
  importSelectedTargetBox: {
    borderRadius: 13,
    borderWidth: 1,
    borderColor: setupColors.borderSoft,
    backgroundColor: setupColors.bg2,
    paddingHorizontal: 11,
    paddingVertical: 8,
    marginTop: 9,
  },
  importChangeSmallButton: {
    alignSelf: 'flex-start',
    minHeight: 28,
    borderRadius: 9,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: setupColors.purpleDark,
    borderColor: setupColors.purple,
    borderWidth: 1,
    marginTop: 7,
  },
  importChangeSmallText: {
    color: setupColors.text,
    fontSize: 10,
    fontWeight: '900',
  },
  importOptionScrollLarge: {
    maxHeight: 260,
    marginTop: 10,
  },


});
