import { StyleSheet } from 'react-native';

export const raceDayColors = {
  bg: '#05070B',
  panel: '#0B0F16',
  card: '#11151F',
  cardAlt: '#0D1320',
  border: '#273143',
  text: '#F7FAFC',
  muted: '#A7B1C2',
  faint: '#6F7D93',
  accent: '#22C55E',
  accentSoft: 'rgba(34,197,94,0.10)',
  accentSofter: 'rgba(34,197,94,0.055)',
  accentBorder: 'rgba(34,197,94,0.78)',
  accentTextDark: '#04130A',
  danger: '#EF4444',
  dangerSoft: 'rgba(239,68,68,0.14)',
  blue: '#38BDF8',
  blueSoft: 'rgba(56,189,248,0.14)',
  purple: '#A78BFA',
  input: '#090D14',
};

export const raceDayStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: raceDayColors.bg,
  },
  container: {
    flex: 1,
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    paddingHorizontal: 25,
  },
  scrollContent: {
    paddingBottom: 28,
  },

  // Header matches the newer IMRC pages: compact, safe-area aware, left aligned title block.
  header: {
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 10,
  },
  headerSide: {
    minWidth: 62,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerSideRight: {
    justifyContent: 'flex-end',
  },
  titleWrap: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    minWidth: 0,
  },
  eyebrow: {
    color: raceDayColors.accent,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: -1,
  },
  title: {
    color: raceDayColors.text,
    fontSize: 27,
    lineHeight: 31,
    fontWeight: '900',
    letterSpacing: -0.7,
    textAlign: 'left',
  },
  subtitle: {
    color: raceDayColors.muted,
    fontSize: 12,
    marginTop: 2,
    textAlign: 'left',
  },
  smallButton: {
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: raceDayColors.cardAlt,
  },
  smallButtonText: {
    color: raceDayColors.text,
    fontSize: 12,
    fontWeight: '900',
  },
  headerActionButton: {
    minHeight: 36,
    paddingHorizontal: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: raceDayColors.accent,
    borderWidth: 1,
    borderColor: raceDayColors.accent,
  },
  headerActionButtonText: {
    color: raceDayColors.accentTextDark,
    fontSize: 12,
    fontWeight: '900',
  },
  headerDangerButton: {
    backgroundColor: raceDayColors.dangerSoft,
    borderColor: 'rgba(239,68,68,0.42)',
  },
  headerDangerButtonText: {
    color: '#FCA5A5',
  },

  primaryButton: {
    minHeight: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: raceDayColors.accent,
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: raceDayColors.accentTextDark,
    fontSize: 15,
    fontWeight: '900',
  },
  secondaryButton: {
    minHeight: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: raceDayColors.cardAlt,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    paddingHorizontal: 16,
  },
  secondaryButtonText: {
    color: raceDayColors.text,
    fontSize: 15,
    fontWeight: '900',
  },
  dangerButton: {
    backgroundColor: raceDayColors.dangerSoft,
    borderColor: 'rgba(239,68,68,0.4)',
  },
  dangerButtonText: {
    color: '#FCA5A5',
  },

  card: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: raceDayColors.card,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    borderRadius: 16,
    padding: 14,
    paddingLeft: 17,
    marginBottom: 10,
  },
  cardAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: raceDayColors.accent,
    opacity: 0.9,
  },
  selectedCard: {
    borderColor: raceDayColors.accentBorder,
    backgroundColor: raceDayColors.accentSoft,
  },
  softSelectedCard: {
    borderColor: raceDayColors.accentBorder,
    backgroundColor: raceDayColors.accentSofter,
  },
  cardTitle: {
    color: raceDayColors.text,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: -0.2,
  },
  cardSub: {
    color: raceDayColors.muted,
    fontSize: 12,
    marginTop: 4,
    lineHeight: 16,
  },
  cardMetaRight: {
    color: raceDayColors.muted,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  dashboardEventName: {
    color: raceDayColors.text,
    fontSize: 13,
    fontWeight: '900',
    marginTop: 6,
    lineHeight: 17,
  },
  dashboardEventDate: {
    color: raceDayColors.muted,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 6,
    lineHeight: 15,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  raceDayTrackCardLayout: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  raceDayTrackCardActions: {
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    gap: 9,
    paddingTop: 1,
  },
  pill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: raceDayColors.cardAlt,
    borderWidth: 1,
    borderColor: raceDayColors.border,
  },
  pillText: {
    color: raceDayColors.muted,
    fontSize: 11,
    fontWeight: '900',
  },
  selectedPill: {
    backgroundColor: raceDayColors.accent,
    borderColor: raceDayColors.accent,
  },
  selectedPillText: {
    color: raceDayColors.accentTextDark,
  },
  input: {
    minHeight: 44,
    color: raceDayColors.text,
    backgroundColor: raceDayColors.input,
    borderColor: raceDayColors.border,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  bottomBar: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    paddingHorizontal: 25,
    paddingTop: 8,
    backgroundColor: raceDayColors.bg,
    borderTopWidth: 1,
    borderTopColor: 'rgba(39,49,67,0.68)',
  },
  bottomRow: {
    flexDirection: 'row',
    gap: 10,
  },
  flex1: {
    flex: 1,
  },
  empty: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: raceDayColors.border,
    backgroundColor: raceDayColors.cardAlt,
  },
  emptyText: {
    color: raceDayColors.muted,
    textAlign: 'center',
    lineHeight: 20,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.72)',
  },
  modalBackdropBottom: {
    justifyContent: 'flex-end',
  },
  modalBackdropCenter: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  modalCard: {
    width: '100%',
    maxWidth: 720,
    maxHeight: '88%',
    alignSelf: 'center',
    backgroundColor: raceDayColors.panel,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    padding: 16,
  },
  centeredModalCard: {
    width: '100%',
    maxWidth: 640,
    maxHeight: '90%',
    borderRadius: 24,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },

  syncPickerContent: {
    paddingTop: 12,
    paddingBottom: 10,
  },
  syncPickerStaticTop: {
    flexShrink: 0,
  },
  syncPickerStaticBottom: {
    flexShrink: 0,
    paddingTop: 8,
  },
  eventPickerUrlHint: {
    color: raceDayColors.muted,
    fontSize: 11,
    marginTop: 7,
    lineHeight: 15,
  },
  eventFindButton: {
    minHeight: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: raceDayColors.cardAlt,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    paddingHorizontal: 16,
    marginTop: 9,
  },
  eventPickerOnlyScroll: {
    height: 230,
    marginTop: 7,
    paddingRight: 4,
  },
  eventPickerOnlyScrollContent: {
    paddingBottom: 4,
  },
  eventPickerEmptyBox: {
    minHeight: 96,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: raceDayColors.border,
    backgroundColor: raceDayColors.cardAlt,
    padding: 12,
  },
  selectedEventSummaryCompact: {
    marginBottom: 8,
    padding: 10,
    borderRadius: 13,
    backgroundColor: raceDayColors.accentSofter,
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.32)',
  },
  eventPickerMessage: {
    color: raceDayColors.muted,
    fontSize: 11,
    marginTop: 7,
    lineHeight: 15,
    textAlign: 'center',
  },
  eventPickerScroll: {
    maxHeight: 285,
    marginTop: 8,
    marginBottom: 10,
    paddingRight: 4,
  },
  eventCard: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: raceDayColors.card,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    borderRadius: 12,
    paddingVertical: 7,
    paddingHorizontal: 11,
    paddingLeft: 15,
    marginBottom: 6,
  },
  selectedEventCard: {
    borderColor: raceDayColors.accentBorder,
    backgroundColor: raceDayColors.accentSofter,
  },
  eventTitle: {
    color: raceDayColors.text,
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '900',
    letterSpacing: -0.15,
  },
  eventDate: {
    color: raceDayColors.muted,
    fontSize: 11,
    lineHeight: 13,
    marginTop: 1,
    fontWeight: '700',
  },
  selectedEventSummary: {
    marginTop: 10,
    marginBottom: 10,
    padding: 11,
    borderRadius: 14,
    backgroundColor: raceDayColors.accentSofter,
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.32)',
  },
  changeEventButton: {
    alignSelf: 'flex-end',
    marginTop: 0,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: raceDayColors.accentSofter,
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.42)',
  },
  changeEventButtonText: {
    color: raceDayColors.accent,
    fontSize: 11,
    fontWeight: '900',
  },

  syncProgressCard: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: raceDayColors.card,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    borderRadius: 14,
    padding: 12,
    paddingLeft: 16,
  },
  syncProgressCardCompact: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: raceDayColors.card,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 11,
    paddingLeft: 15,
  },
  syncStatusPill: {
    minWidth: 48,
    minHeight: 28,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: raceDayColors.cardAlt,
    paddingHorizontal: 8,
  },
  syncStatusPillText: {
    fontSize: 10,
    fontWeight: '900',
  },
  syncProgressMessage: {
    color: raceDayColors.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 8,
  },
  syncMetaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 9,
  },
  syncMetaBox: {
    flexGrow: 1,
    minWidth: '44%',
    backgroundColor: raceDayColors.cardAlt,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: 'rgba(39,49,67,0.78)',
    paddingHorizontal: 9,
    paddingVertical: 8,
  },
  syncMetaValue: {
    color: raceDayColors.text,
    fontSize: 12,
    fontWeight: '900',
    marginTop: 2,
  },
  syncMetaGridCompact: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  },
  syncMetaBoxCompact: {
    flexGrow: 1,
    minWidth: '30%',
    backgroundColor: raceDayColors.cardAlt,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(39,49,67,0.72)',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  syncCompleteText: {
    color: raceDayColors.text,
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 10,
  },
  modalTitle: {
    color: raceDayColors.text,
    fontSize: 18,
    fontWeight: '900',
  },
  modalSub: {
    color: raceDayColors.muted,
    fontSize: 12,
    marginTop: 4,
    lineHeight: 18,
  },

  raceRunList: {
    marginTop: 8,
    gap: 6,
  },
  raceRunCard: {
    backgroundColor: raceDayColors.cardAlt,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(39,49,67,0.86)',
    padding: 10,
  },
  raceRunCardThin: {
    backgroundColor: raceDayColors.cardAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(39,49,67,0.82)',
    paddingVertical: 7,
    paddingHorizontal: 8,
  },
  raceRunTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  raceRunTitle: {
    color: raceDayColors.text,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: -0.1,
  },
  raceRunTitleThin: {
    flex: 1,
    color: raceDayColors.text,
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '900',
    letterSpacing: -0.1,
  },
  raceRunSub: {
    color: raceDayColors.muted,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  raceRunStatsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 5,
    marginTop: 6,
  },
  raceRunStatBox: {
    flex: 1,
    minWidth: 0,
    backgroundColor: raceDayColors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(39,49,67,0.72)',
    paddingHorizontal: 6,
    paddingVertical: 5,
  },
  raceRunStatLabel: {
    color: raceDayColors.faint,
    fontSize: 8.5,
    lineHeight: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  raceRunStatValue: {
    color: raceDayColors.text,
    fontSize: 11.5,
    lineHeight: 14,
    fontWeight: '900',
    marginTop: 1,
  },
  resultsMiniButton: {
    minHeight: 28,
    paddingHorizontal: 9,
    borderRadius: 999,
    backgroundColor: raceDayColors.card,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultsMiniButtonText: {
    color: raceDayColors.muted,
    fontSize: 10.5,
    fontWeight: '900',
  },
  statGridCompact: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 8,
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  statBox: {
    flexGrow: 1,
    minWidth: '30%',
    backgroundColor: raceDayColors.cardAlt,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    padding: 10,
  },
  statLabel: {
    color: raceDayColors.faint,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  statValue: {
    color: raceDayColors.text,
    fontSize: 14,
    fontWeight: '900',
    marginTop: 3,
  },
  resultDetailCard: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: raceDayColors.card,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
  },
  resultTop5Button: {
    minHeight: 32,
    paddingHorizontal: 11,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: raceDayColors.accentSofter,
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.42)',
  },
  resultTop5ButtonText: {
    color: raceDayColors.accent,
    fontSize: 11,
    fontWeight: '900',
  },
  dashboardBlockHintBox: {
    marginTop: 11,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: raceDayColors.accentSofter,
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.28)',
  },
  dashboardBlockHintTitle: {
    color: raceDayColors.accent,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  dashboardBlockHintText: {
    color: raceDayColors.muted,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 2,
    fontWeight: '700',
  },
  resultSectionTitle: {
    color: raceDayColors.accent,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
    marginTop: 13,
    marginBottom: 6,
  },
  resultStatGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  resultStatBox: {
    flexGrow: 1,
    minWidth: '30%',
    backgroundColor: raceDayColors.cardAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(39,49,67,0.78)',
    paddingHorizontal: 9,
    paddingVertical: 8,
  },
  resultStatBoxSelectable: {
    borderColor: 'rgba(39,49,67,0.92)',
  },
  resultStatBoxSelected: {
    backgroundColor: raceDayColors.accentSoft,
    borderColor: raceDayColors.accentBorder,
  },
  resultStatHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  resultShownBadge: {
    color: raceDayColors.accent,
    fontSize: 8.5,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  resultStatBoxWide: {
    minWidth: '100%',
  },
  resultStatValue: {
    color: raceDayColors.text,
    fontSize: 13,
    fontWeight: '900',
    marginTop: 3,
  },

  top5List: {
    gap: 8,
  },
  top5DetailCard: {
    backgroundColor: raceDayColors.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(39,49,67,0.84)',
    padding: 10,
  },
  top5MeCard: {
    backgroundColor: raceDayColors.accentSofter,
    borderColor: raceDayColors.accentBorder,
  },
  top5StatGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 9,
  },
  top5StatBox: {
    flexGrow: 1,
    minWidth: '30%',
    backgroundColor: raceDayColors.cardAlt,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(39,49,67,0.72)',
    paddingHorizontal: 7,
    paddingVertical: 6,
  },
  top5StatLabel: {
    color: raceDayColors.faint,
    fontSize: 8.5,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  top5StatValue: {
    color: raceDayColors.text,
    fontSize: 11.5,
    lineHeight: 14,
    fontWeight: '900',
    marginTop: 1,
  },
  top5VerifyText: {
    color: raceDayColors.muted,
    fontSize: 10.5,
    lineHeight: 14,
    fontWeight: '800',
    marginTop: 8,
  },

  top5PopupContent: {
    paddingTop: 6,
    paddingBottom: 4,
  },
  top5CompactShell: {
    gap: 3,
  },
  top5ScrollHint: {
    color: raceDayColors.faint,
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 0,
  },
  top5HorizontalScrollContent: {
    paddingBottom: 2,
  },
  top5Table: {
    minWidth: 926,
    overflow: 'hidden',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(39,49,67,0.88)',
    backgroundColor: raceDayColors.card,
  },
  top5TableRow: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(39,49,67,0.46)',
  },
  top5TableHeaderRow: {
    minHeight: 24,
    backgroundColor: raceDayColors.cardAlt,
  },
  top5TableRowAlt: {
    backgroundColor: 'rgba(255,255,255,0.018)',
  },
  top5TableMeRow: {
    backgroundColor: raceDayColors.accentSofter,
  },
  top5TableText: {
    color: raceDayColors.text,
    fontSize: 10.5,
    lineHeight: 13,
    fontWeight: '900',
    paddingHorizontal: 5,
  },
  top5MeText: {
    color: raceDayColors.accent,
  },
  top5ColPos: {
    width: 40,
  },
  top5ColDriver: {
    width: 126,
  },
  top5ColMed: {
    width: 80,
  },
  top5ColSmall: {
    width: 66,
  },
  top5ColVerify: {
    width: 80,
    color: raceDayColors.muted,
  },

  lapListBox: {
    backgroundColor: raceDayColors.cardAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(39,49,67,0.78)',
    overflow: 'hidden',
  },
  lapRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(39,49,67,0.45)',
  },
  lapNum: {
    width: 42,
    color: raceDayColors.faint,
    fontSize: 11,
    fontWeight: '900',
  },
  lapTime: {
    flex: 1,
    color: raceDayColors.text,
    fontSize: 12,
    fontWeight: '900',
  },
  lapTotal: {
    flex: 1,
    color: raceDayColors.muted,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'right',
  },

  raceDayNotesDashboardCard: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: raceDayColors.card,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    borderRadius: 16,
    padding: 13,
    paddingLeft: 17,
    marginBottom: 10,
  },
  raceDayNotesOpenBadge: {
    minHeight: 31,
    paddingHorizontal: 13,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: raceDayColors.accentBorder,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: raceDayColors.accentSofter,
  },
  raceDayNotesOpenBadgeText: {
    color: raceDayColors.accent,
    fontSize: 11,
    fontWeight: '900',
  },
  raceDayNotesPopupBody: {
    gap: 10,
  },
  raceDayNotesPanel: {
    backgroundColor: raceDayColors.cardAlt,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    borderRadius: 16,
    padding: 12,
    gap: 10,
  },
  raceDayNotesLabel: {
    color: raceDayColors.text,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: -0.1,
  },
  raceDayNotesInput: {
    minHeight: 108,
    maxHeight: 180,
    color: raceDayColors.text,
    backgroundColor: raceDayColors.input,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  raceDayNotesHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 2,
  },
  raceDayChangesList: {
    maxHeight: 315,
  },
  raceDayVehicleChangeSection: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: raceDayColors.card,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    borderRadius: 15,
    padding: 11,
    marginBottom: 9,
  },
  raceDayVehicleChangeTitle: {
    flex: 1,
    color: raceDayColors.text,
    fontSize: 14,
    fontWeight: '900',
  },
  raceDayChangeRow: {
    backgroundColor: raceDayColors.cardAlt,
    borderWidth: 1,
    borderColor: 'rgba(39,49,67,0.8)',
    borderRadius: 12,
    padding: 9,
    marginTop: 8,
  },
  raceDayChangeField: {
    flex: 1,
    color: raceDayColors.text,
    fontSize: 12,
    fontWeight: '900',
  },
  raceDayChangeTime: {
    color: raceDayColors.faint,
    fontSize: 10,
    fontWeight: '800',
  },
  raceDayChangeSetup: {
    color: raceDayColors.muted,
    fontSize: 10.5,
    fontWeight: '800',
    marginTop: 2,
  },
  raceDayChangeValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 7,
  },
  raceDayChangeOld: {
    flex: 1,
    color: raceDayColors.muted,
    fontSize: 11,
    fontWeight: '800',
    backgroundColor: raceDayColors.input,
    borderRadius: 9,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  raceDayChangeArrow: {
    color: raceDayColors.accent,
    fontSize: 13,
    fontWeight: '900',
  },
  raceDayChangeNew: {
    flex: 1,
    color: raceDayColors.text,
    fontSize: 11,
    fontWeight: '900',
    backgroundColor: raceDayColors.accentSofter,
    borderRadius: 9,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  raceDayChangeNote: {
    color: raceDayColors.muted,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 6,
  },
  raceDayEmptyChangesBox: {
    backgroundColor: raceDayColors.cardAlt,
    borderWidth: 1,
    borderColor: raceDayColors.border,
    borderRadius: 15,
    padding: 14,
  },

});
